INSERT INTO card (card_name) VALUES ('Kaust, Eyes of the Glade');
INSERT INTO card (card_name) VALUES ('Duskana, the Rage Mother');
INSERT INTO card (card_name) VALUES ('True Identity');
INSERT INTO card (card_name) VALUES ('Unexplained Absence');
INSERT INTO card (card_name) VALUES ('Veiled Ascension');
INSERT INTO card (card_name) VALUES ('Boltbender');
INSERT INTO card (card_name) VALUES ('Showstopping Surprise');
INSERT INTO card (card_name) VALUES ('Tesak, Judiths Hellhound');
INSERT INTO card (card_name) VALUES ('Experiment Twelve');
INSERT INTO card (card_name) VALUES ('Printlifter Ooze');
INSERT INTO card (card_name) VALUES ('Panoptic Projektor');
INSERT INTO card (card_name) VALUES ('Ransom Note (Morph)');
INSERT INTO card (card_name) VALUES ('Ugins Mastery');
INSERT INTO card (card_name) VALUES ('Austere Command');
INSERT INTO card (card_name) VALUES ('Dusk /// Dawn');
INSERT INTO card (card_name) VALUES ('Exalted Angel');
INSERT INTO card (card_name) VALUES ('Fell the Mighty');
INSERT INTO card (card_name) VALUES ('Hidden Dragonslayer');
INSERT INTO card (card_name) VALUES ('Master of Pearls');
INSERT INTO card (card_name) VALUES ('Mastery of the Unseen');
INSERT INTO card (card_name) VALUES ('Mirror Entity');
INSERT INTO card (card_name) VALUES ('Welcoming Vampire');
INSERT INTO card (card_name) VALUES ('Akroma, Angel of Fury');
INSERT INTO card (card_name) VALUES ('Ashcloud Phoenix');
INSERT INTO card (card_name) VALUES ('Chaos Warp');
INSERT INTO card (card_name) VALUES ('Imperial Hellkite');
INSERT INTO card (card_name) VALUES ('Jeskas Will');
INSERT INTO card (card_name) VALUES ('Neheb, the Eternal');
INSERT INTO card (card_name) VALUES ('Scourge of the Throne');
INSERT INTO card (card_name) VALUES ('Beast Whisperer');
INSERT INTO card (card_name) VALUES ('Deathmist Raptor');
INSERT INTO card (card_name) VALUES ('Den Protector');
INSERT INTO card (card_name) VALUES ('Hooded Hydra');
INSERT INTO card (card_name) VALUES ('Krosan Cloudscraper');
INSERT INTO card (card_name) VALUES ('Krosan Colossus');
INSERT INTO card (card_name) VALUES ('Obscuring Aether');
INSERT INTO card (card_name) VALUES ('Ohran Frostfang');
INSERT INTO card (card_name) VALUES ('Return of the Wildspeaker');
INSERT INTO card (card_name) VALUES ('Root Elemental');
INSERT INTO card (card_name) VALUES ('Saryth, the Vipers Fang');
INSERT INTO card (card_name) VALUES ('Seedborn Muse');
INSERT INTO card (card_name) VALUES ('Temur War Shaman');
INSERT INTO card (card_name) VALUES ('Thelonite Hermit');
INSERT INTO card (card_name) VALUES ('Toski, Bearer of Secrets');
INSERT INTO card (card_name) VALUES ('Trail of Mystery');
INSERT INTO card (card_name) VALUES ('Whisperwood Elemental');
INSERT INTO card (card_name) VALUES ('Yedora, Grave Gardener');
INSERT INTO card (card_name) VALUES ('Decimate');
INSERT INTO card (card_name) VALUES ('Sidar Kondo of Jamuraa');
INSERT INTO card (card_name) VALUES ('Lifecrafters Bestiary');
INSERT INTO card (card_name) VALUES ('Scroll of Fate');
INSERT INTO card (card_name) VALUES ('Canopy Vista');
INSERT INTO card (card_name) VALUES ('Cinder Glade');
INSERT INTO card (card_name) VALUES ('Exotic Orchard');
INSERT INTO card (card_name) VALUES ('Fortified Village');
INSERT INTO card (card_name) VALUES ('Furycalm Snarl');
INSERT INTO card (card_name) VALUES ('Game Trail');
INSERT INTO card (card_name) VALUES ('Kessig Wolf Run');
INSERT INTO card (card_name) VALUES ('Mossfire Valley');
INSERT INTO card (card_name) VALUES ('Mosswort Bridge');
INSERT INTO card (card_name) VALUES ('Scattered Groves');
INSERT INTO card (card_name) VALUES ('Sheltered Thicket');
INSERT INTO card (card_name) VALUES ('Shrine of the Forsaken Gods');
INSERT INTO card (card_name) VALUES ('Sungrass Prairie');
INSERT INTO card (card_name) VALUES ('Temple of Abandon');
INSERT INTO card (card_name) VALUES ('Temple of Plenty');
INSERT INTO card (card_name) VALUES ('Temple of Triumph');
INSERT INTO card (card_name) VALUES ('Path to Exile');
INSERT INTO card (card_name) VALUES ('Ainok Survivalist');
INSERT INTO card (card_name) VALUES ('Broodhatch Nantuko');
INSERT INTO card (card_name) VALUES ('Nervous Gardener');
INSERT INTO card (card_name) VALUES ('Nantuko Vigilante');
INSERT INTO card (card_name) VALUES ('Natures Lore');
INSERT INTO card (card_name) VALUES ('Sakura-Tribe Elder');
INSERT INTO card (card_name) VALUES ('Salt Road Ambushers');
INSERT INTO card (card_name) VALUES ('Three Visits');
INSERT INTO card (card_name) VALUES ('Wild Growth');
INSERT INTO card (card_name) VALUES ('Arcane Signet');
INSERT INTO card (card_name) VALUES ('Sol Ring');
INSERT INTO card (card_name) VALUES ('Boros Garrison');
INSERT INTO card (card_name) VALUES ('Command Tower');
INSERT INTO card (card_name) VALUES ('Branch of Vitu-Ghazi');
INSERT INTO card (card_name) VALUES ('Gruul Turf');
INSERT INTO card (card_name) VALUES ('Jungle Shrine');
INSERT INTO card (card_name) VALUES ('Krosan Verge');
INSERT INTO card (card_name) VALUES ('Sacred Peaks');
INSERT INTO card (card_name) VALUES ('Selesnya Sanctuary');
INSERT INTO card (card_name) VALUES ('Temple of the False God');
INSERT INTO card (card_name) VALUES ('Zoetic Cavern');

